version: '3.7'
services:

  # The Application
  app:
    build:
      context: ./docker/
      dockerfile: app.dockerfile
    image: app-advicehealth
    container_name: advicehealth-app
    tty: true
    working_dir: /var/www
    volumes:
      - ./src/:/var/www
    environment:
      DB_PORT: 3306
      DB_HOST: database
      TZ: 'America/Sao_Paulo'
      PHP_REDIS_SESSION_HOST: 'redis'
      CREATE_LARAVEL_STORAGE: '1'
    networks:
      - net

  # The Web Server
  web:
    build:
      context: ./docker/
      dockerfile: web.dockerfile
    image: web-advicehealth
    container_name: advicehealth-web
    tty: true
    working_dir: /var/www
    ports:
      - 8086:80
    networks:
      - net

  # The Database
  database:
    build:
      context: ./docker/
      dockerfile: db.dockerfile
    image: database-advicehealth
    container_name: advicehealth-database
    tty: true
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3386:3306
    networks:
      - net

  redis:
    build:
      context: ./docker/
      dockerfile: redis.dockerfile
    image: redis-advicehealth
    container_name: advicehealth-redis
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'redis:/data'
    networks:
      - net

volumes:
  dbdata:
    driver: local
  redis:
    driver: local
networks:
  net:
    driver: "bridge"
