version: '3.7'
services:

  # The Api Server
  api:
    build:
      context: ./docker/
      dockerfile: api.dockerfile
    image: api-advicehealth
    container_name: advicehealth-api
    tty: true
    working_dir: /var/www
    command:
      [
        'bash',
        '-c',
        'php artisan serve --host=0.0.0.0 --port=9000'
      ]
    volumes:
      - ./api/:/var/www
    environment:
      DB_PORT: 3306
      DB_HOST: database
      TZ: 'America/Sao_Paulo'
      PHP_REDIS_SESSION_HOST: 'redis'
      CREATE_LARAVEL_STORAGE: '1'
    ports:
      - 9000:9000
    networks:
      - net

  # The Vue Server
  app:
    build:
      context: ./docker/
      dockerfile: app.dockerfile
    image: app-advicehealth
    container_name: advicehealth-app
    working_dir: /home/node/app
    command: [ 'bash', '-c', 'yarn serve' ]
    environment:
      - NODE_ENV=development
    volumes:
      - ./app:/home/node/app
    ports:
      - 8080:8080
    networks:
      - net

  # The Web Server
  web:
    build:
      context: ./docker/
      dockerfile: web.dockerfile
    image: web-advicehealth
    container_name: advicehealth-web
    tty: true
    working_dir: /var/www
    ports:
      - 80:80
    networks:
      - net

  # The Database
  database:
    build:
      context: ./docker/
      dockerfile: db.dockerfile
    image: database-advicehealth
    container_name: advicehealth-database
    tty: true
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3386:3306
    networks:
      - net

  # The Redis
  redis:
    build:
      context: ./docker/
      dockerfile: redis.dockerfile
    image: redis-advicehealth
    container_name: advicehealth-redis
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'redis:/data'
    networks:
      - net

volumes:
  dbdata:
    driver: local
  redis:
    driver: local
networks:
  net:
    driver: "bridge"
